// <auto-generated />
using BusinessPortal2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessPortal2.Migrations
{
    [DbContext(typeof(PersonaldataContext))]
    partial class PersonaldataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessPortal2.Models.LeaveType", b =>
                {
                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("Sick")
                        .HasColumnType("int");

                    b.Property<int>("Vabb")
                        .HasColumnType("int");

                    b.Property<int>("Vacation")
                        .HasColumnType("int");

                    b.HasKey("PersonalId");

                    b.ToTable("leaveTypes");
                });

            modelBuilder.Entity("BusinessPortal2.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("personals");
                });

            modelBuilder.Entity("BusinessPortal2.Models.LeaveType", b =>
                {
                    b.HasOne("BusinessPortal2.Models.Personal", "Personal")
                        .WithOne("leavetype")
                        .HasForeignKey("BusinessPortal2.Models.LeaveType", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("BusinessPortal2.Models.Personal", b =>
                {
                    b.Navigation("leavetype")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
